// src/components/Header.vue
<template>
    <header class="p-4 flex justify-between items-center bg-transparent\">
      <div class="text-xl font-bold\">Цветочная лавка</div>
      <nav class="space-x-4\">
        <button class="px-4 py-2 bg-gray-300 rounded\">Профиль</button>
        <button class="px-4 py-2 bg-gray-300 rounded\">Избранное</button>
        <button class="px-4 py-2 bg-gray-300 rounded\">Корзина</button>
      </nav>
    </header>
  </template>
  
  <script setup></script>

// src/components/Header.jsx
import { Link } from "react-router-dom";

export default function Header() {
  return (
    <header className="flex justify-between items-center p-4 bg-[#eee] shadow">
      <Link to="/" className="text-xl font-bold">Цветочная лавка</Link>
      <nav className="flex gap-4">
        <Link to="/favorites" className="px-3 py-1 rounded bg-slate-200">Избранное</Link>
      </nav>
    </header>
  );
}
